#!/bin/bash

echo
echo pickles recursively looks for all wav files in your samples folder.
echo Each file will be played, and you must assign it to a folder.
echo If you leave a blank folder name, the file will be removed.
echo If in doubt, just assign the file back to the samples folder.

find samples -name "*.wav" -print0 | while read -d $'\0' file
do
    echo
    echo "Playing $file"
    ffplay -autoexit -nodisp "$file" > /dev/null 2>&1
    read -p "Folder: " folder < /dev/tty
    if [ -z "$folder" ]
    then
        rm "$file"
        echo "Removed $file"
    else
        mkdir -p "$folder"
        name=$(basename "$file")
        path=$(echo "$folder/$name")
        mv "$file" "$path"
        echo "Moved $file to $path"
    fi
done
